spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mp
    password: XueGod!@#123
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai

logging:
  level:
    root: warn
    com.mp.dao: trace
  pattern:
    console: '%p%m%n'
    
mybatis-plus:
  mapper-locations:
  - com/mp/mapper/*.xml    